# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: pb_development
  pool: 5
  username: photo_blog
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pb_test
  pool: 5
  username: photo_blog
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: pb_production
  pool: 5
  username: photo_blog


